#!/sbin/openrc-run
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/cloudflared"
command_args="--no-autoupdate tunnel run ${CLOUDFLARED_OPTS}"
command_background="yes"
command_user="${USER:-cloudflared}:${GROUP:-cloudflared}"
description="Cloudflare Tunnel client"
name="Cloudflare Tunnel client"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need net
}
